<a href="https://colab.research.google.com/github/icarito/UPSK-SQL001-SQLZoo-murder/blob/sql-murder/Sql-Murder-Mystery/SQL_Murder_Mystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Murder Mystery!
Adapted By: Martin Arroyo

![Detective making connections between points](https://github.com/freestackinitiative/coop_sql_notebooks/blob/main/assets/sleuth.png?raw=1)

**Credit**

This material was adapted from the [SQL Murder Mystery by Knight Lab](https://mystery.knightlab.com/) under [Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). The SQL Murder Mystery was originally created by [Joon Park](https://twitter.com/joonparkmusic) and [Cathy He](https://twitter.com/Cathy_MeiyingHe) while they were Knight Lab fellows. See the [GitHub repository](https://github.com/NUKnightLab/sql-mysteries) for more information.

## Escenario

¡Se ha cometido un crimen y los detectives necesitan tu ayuda! Te dieron el informe de la escena del crimen, pero de alguna manera lo perdiste. Recuerdas vagamente que el crimen fue un `murder` _(asesinato)_ que ocurrió en algún momento el 15 de Enero de 2018 y que tuvo lugar en `SQL City`. Depende de ti averiguar quién es el asesino usando solo tus habilidades en SQL y tu ingenio. Te proporcionan una conexión a la base de datos del Departamento de Policía, que tiene todas las pistas que necesitarás para atrapar al asesino.

Usa las habilidades que desarrollaste en SQL 101 y 102, junto con cualquier recurso que desees, para resolver el `SQL Murder Mystery`!"

## Conéctate a la base de datos del Departamento de Policía

Para comenzar y ejecutar tus consultas, presiona play en la celda de abajo para conectarte a la base de datos del Departamento de Policía.

Para ejecutar consultas, crea una nueva celda de `Code` y escribe `%%sql` en la parte superior. Luego puedes escribir tus consultas debajo. Ve el ejemplo a continuación:
```python
%%sql

SELECT *
FROM table

```

In [6]:
%%capture
# @title Press Play { display-mode: "form" }
# Install `teachdb` and `coop_grader`
print("Installing `teachdb` and its dependencies...")
!pip install --quiet --upgrade git+https://github.com/freestackinitiative/teachingdb.git git+https://github.com/martinmarroyo/coop_grader.git
print("Successfully installed `teachdb`")
import pandas as pd
from teachdb.teachdb import connect_teachdb
from coop_grader.sql_murder_mystery.check_suspect import check_suspect
# Set configurations for notebook
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 99)
# Load data
con = connect_teachdb(database="sql_murder_mystery")

%sql con

## Descubriendo tablas en la base de datos

Comenzamos nuestra búsqueda para encontrar al asesino explorando la base de datos del Departamento de Policía. Pero aún no has visto la base de datos y no sabes cuáles son las tablas, así que, ¿cómo sabes qué buscar?

Afortunadamente, la mayoría de los sistemas de gestión de bases de datos relacionales tienen esta información almacenada en un lugar donde puedes consultarla. Muy a menudo, se utiliza un esquema especial conocido como [`information_schema`](https://en.wikipedia.org/wiki/Information_schema) para almacenar información sobre las tablas y columnas en tu base de datos (también conocido como metadata). La base de datos del Departamento de Policía tiene un information schema, con la vista `tables` que te muestra qué tablas están disponibles, y la vista `columns` que te muestra todas las columnas de cada tabla y sus tipos de datos.

### Listando todas las tablas en la base de datos de la Policía

#### Revisa la [descripción de `information_schema.tables`](https://duckdb.org/docs/sql/information_schema.html#tables-and-views)

Primero, veremos todas las tablas disponibles para nosotros consultando la vista `information_schema.tables`. Te daremos la primera consulta para empezar, pero de aquí en adelante tendrás que idear las consultas restantes utilizando tu conocimiento de SQL y tu ingenio.

Aquí está la consulta necesaria para mostrarte las tablas en la base de datos del Departamento de Policía. Cópiala/Pégala en la celda de abajo y ejecútala para ver las tablas disponibles para ti:

>```sql
>SELECT *
>FROM information_schema.tables
>```

In [ ]:
%%sql
/*
  Solicitar todas las columnas de la tabla information_schema.tables
*/
SELECT *
FROM information_schema.tables

table_catalog table_schema              table_name  table_type self_referencing_column_name  \
0        memory         main      crime_scene_report  BASE TABLE                         None   
1        memory         main         drivers_license  BASE TABLE                         None   
2        memory         main  facebook_event_checkin  BASE TABLE                         None   
3        memory         main    get_fit_now_check_in  BASE TABLE                         None   
4        memory         main      get_fit_now_member  BASE TABLE                         None   
5        memory         main                  income  BASE TABLE                         None   
6        memory         main               interview  BASE TABLE                         None   
7        memory         main                  person  BASE TABLE                         None   

  reference_generation user_defined_type_catalog user_defined_type_schema user_defined_type_name  \
0                 None                      None                     None                   None   
1                 None                      None                     None                   None   
2                 None                      None                     None                   None   
3                 None                      None                     None                   None   
4                 None                      None                     None                   None   
5                 None                      None                     None                   None   
6                 None                      None                     None                   None   
7                 None                      None                     None                   None   

  is_insertable_into is_typed commit_action TABLE_COMMENT  
0                YES       NO          None          None  
1                YES       NO          None          None  
2                YES       NO          None          None  
3                YES       NO          None          None  
4                YES       NO          None          None  
5                YES       NO          None          None  
6                YES       NO          None          None  
7                YES       NO          None          None

### Listando todas las tablas y sus columnas en la base de datos de la Policía

**Revisa la [descripción de `information_schema.columns`](https://duckdb.org/docs/sql/information_schema.html#columns)**

¡Genial! Ahora que sabes qué tablas están disponibles, es hora de averiguar las columnas que tiene cada tabla junto con el tipo de datos de cada columna. Escribe una consulta que muestre el nombre de la tabla, el nombre de la columna y el tipo de datos para cada tabla en la base de datos del Departamento de Policía utilizando la vista `information_schema.columns`. Asegúrate de que la salida esté ordenada por nombre de tabla y luego por nombre de columna (ascendente):

*Pistas opcionales - ¡intenta usarlas solo si te quedas **REALMENTE** atascado!*

<details>
<summary>Pista 1</summary>
<p>Estructura tu consulta de la misma manera que lo hicimos en la consulta anterior donde miramos `information_schema.tables`</p>
</details>

<details>
<summary>Pista 2</summary>
<p>Asegúrate de revisar el enlace para la descripción de information_schema.columns. Te dirá los nombres de las columnas que debes usar para la consulta. Recuerda, queremos el nombre de la tabla, el nombre de la columna y el tipo de datos - ¡revisa la descripción para encontrar los nombres apropiados!</p>
</details>

<details>
<summary>Pista 3</summary>
<p>No olvides usar la declaración ORDER BY para ordenar los resultados de tu búsqueda. Estamos buscando ordenar ambas columnas en orden ascendente, lo cual se puede especificar usando la palabra clave ASC, sin embargo, también es el orden de clasificación predeterminado, por lo que ASC no es necesariamente requerido.</p>
</details>

In [ ]:
%%sql
/*
  consulta que muestre el nombre de la tabla, el nombre de la columna y
  el tipo de datos para cada tabla en la base de datos
  del Departamento de Policía utilizando la vista information_schema.columns
*/
FROM
    information_schema.columns
ORDER BY
    table_name ASC,
    column_name ASC;

table_catalog table_schema              table_name            column_name  ordinal_position  \
0         memory         main      crime_scene_report                   city                 4   
1         memory         main      crime_scene_report                   date                 1   
2         memory         main      crime_scene_report            description                 3   
3         memory         main      crime_scene_report                   type                 2   
4         memory         main         drivers_license                    age                 2   
5         memory         main         drivers_license               car_make                 8   
6         memory         main         drivers_license              car_model                 9   
7         memory         main         drivers_license              eye_color                 4   
8         memory         main         drivers_license                 gender                 6   
9         memory         main         drivers_license             hair_color                 5   
10        memory         main         drivers_license                 height                 3   
11        memory         main         drivers_license                     id                 1   
12        memory         main         drivers_license           plate_number                 7   
13        memory         main  facebook_event_checkin                   date                 4   
14        memory         main  facebook_event_checkin               event_id                 2   
15        memory         main  facebook_event_checkin             event_name                 3   
16        memory         main  facebook_event_checkin              person_id                 1   
17        memory         main    get_fit_now_check_in          check_in_date                 2   
18        memory         main    get_fit_now_check_in          check_in_time                 3   
19        memory         main    get_fit_now_check_in         check_out_time                 4   
20        memory         main    get_fit_now_check_in          membership_id                 1   
21        memory         main      get_fit_now_member                     id                 1   
22        memory         main      get_fit_now_member  membership_start_date                 4   
23        memory         main      get_fit_now_member      membership_status                 5   
24        memory         main      get_fit_now_member                   name                 3   
25        memory         main      get_fit_now_member              person_id                 2   
26        memory         main                  income          annual_income                 2   
27        memory         main                  income                    ssn                 1   
28        memory         main               interview              person_id                 1   
29        memory         main               interview             transcript                 2   
30        memory         main                  person         address_number                 4   
31        memory         main                  person    address_street_name                 5   
32        memory         main                  person                     id                 1   
33        memory         main                  person             license_id                 3   
34        memory         main                  person                   name                 2   
35        memory         main                  person                    ssn                 6   

   column_default is_nullable data_type  character_maximum_length  character_octet_length  \
0            None         YES   VARCHAR                       NaN                     NaN   
1            None         YES    BIGINT                       NaN                     NaN   
2            None         YES   VARCHAR                       NaN                     NaN   
3   

### Entity Relationship Diagram (Optional)

After doing some detective work and finding the tables in the Police Department database, you discover that there is an ERD! This can be really helpful in your quest to find the murderer. If you like, challenge yourself (and your SQL skills) to continue on by just querying the `information_schema` as needed. Otherwise, you can click the dropdown below to reveal the ERD to help you see the tables and relationships in the Police Department database at a glance:

<details>
  <summary>Check the SQL Murder Mystery ERD</summary>
  <img src="https://github.com/freestackinitiative/coop_sql_notebooks/blob/main/assets/murder_mystery_schema.png?raw=1" alt="ERD for SQL Murder Mystery"/>
</details>

### Diagrama de Relaciones de Entidad (Opcional)

Después de hacer un poco de trabajo de detective y encontrar las tablas en la base de datos del Departamento de Policía, descubres que hay un ERD (Diagrama de Relaciones de Entidad). Esto puede ser realmente útil en tu búsqueda para encontrar al asesino. Si lo prefieres, desafíate a ti mismo (y tus habilidades en SQL) a continuar solo consultando el `information_schema` según sea necesario. De lo contrario, puedes hacer clic en el desplegable a continuación para revelar el ERD que te ayudará a ver las tablas y las relaciones en la base de datos del Departamento de Policía de un vistazo:

<details>
  <summary>Revisa el ERD del SQL Murder Mystery</summary>
  <img src="https://github.com/freestackinitiative/coop_sql_notebooks/blob/main/assets/murder_mystery_schema.png?raw=1" alt="ERD for SQL Murder Mystery"/>
</details>

In [7]:
%%sql
/*
  ver informacion de la tabla crime_scene_report
*/
SELECT *
FROM crime_scene_report;


date       type  \
0     20180115    robbery   
1     20180115     murder   
2     20180115     murder   
3     20180215     murder   
4     20180215     murder   
5     20180115      theft   
6     20180115      fraud   
7     20170712      theft   
8     20170820      arson   
9     20171110    robbery   
10    20180103    bribery   
11    20180115    assault   
12    20180115    assault   
13    20170101      fraud   
14    20170101      fraud   
15    20170101      theft   
16    20170101  smuggling   
17    20170101    assault   
18    20170102      arson   
19    20170102    bribery   
20    20170102      theft   
21    20170102  smuggling   
22    20170103      arson   
23    20170104  blackmail   
24    20170105      theft   
25    20170105    robbery   
26    20170106  blackmail   
27    20170106  blackmail   
28    20170106      theft   
29    20170107    bribery   
30    20170107  smuggling   
31    20170107  blackmail   
32    20170107      theft   
33    20170107     murder   
34    20170108     murder   
35    20170108      theft   
36    20170108     murder   
37    20170109    robbery   
38    20170109      fraud   
39    20170109      arson   
40    20170109      arson   
41    20170109    bribery   
42    20170110  blackmail   
43    20170111     murder   
44    20170111    bribery   
45    20170112  smuggling   
46    20170113      fraud   
47    20170113  blackmail   
48    20170113    assault   
49    20170114      fraud   
50    20170114  blackmail   
51    20170114      fraud   
52    20170115    assault   
53    20170115      theft   
54    20170115    robbery   
55    20170116  blackmail   
56    20170116    assault   
57    20170116  blackmail   
58    20170116    bribery   
59    20170116  smuggling   
60    20170117    assault   
61    20170117    bribery   
62    20170118    robbery   
63    20170118      arson   
64    20170118      theft   
65    20170119  smuggling   
66    20170119    robbery   
67    20170121      arson   
68    20170121     murder   
69    20170122    robbery   
70    20170122    bribery   
71    20170122    bribery   
72    20170122     murder   
73    20170122    assault   
74    20170123  blackmail   
75    20170123    assault   
76    20170124      arson   
77    20170124     murder   
78    20170124    robbery   
79    20170124     murder   
80    20170125     murder   
81    20170125      theft   
82    20170126      arson   
83    20170127      arson   
84    20170127  blackmail   
85    20170128      theft   
86    20170128      theft   
87    20170128    assault   
88    20170129      arson   
89    20170129    bribery   
90    20170129  blackmail   
91    20170129    robbery   
92    20170129    assault   
93    20170130      fraud   
94    20170130      arson   
95    20170130      fraud   
96    20170131    bribery   
97    20170131    bribery   
98    20170131    bribery   
99    20170201      fraud   
100   20170202  blackmail   
101   20170202    robbery   
102   20170202  smuggling   
103   20170202  smuggling   
104   20170203      arson   
105   20170203  smuggling   
106   20170204  blackmail   
107   20170204      theft   
108   20170205    robbery   
109   20170205    robbery   
110   20170205  smuggling   
111   20170205    bribery   
112   20170205      fraud   
113   20170207      arson   
114   20170207     murder   
115   20170207      arson   
116   20170208      theft   
117   20170208      fraud   
118   20170208      fraud   
119   20170208  smuggling   
120   20170209  smuggling   
121   20170209  smuggling   
122   20170210    assault   
123   20170210      arson   
124   20170210  blackmail   
125   20170210    bribery   
126   20170211      arson   
127   20170212      fraud   
128   20170212    assault   
129   20170212    robbery   
130   20170212    bribery   
131   20170214      fraud   
132   20170214      fraud   
133   20170214    assault   
134   20170214    bribery   
135   20170215      arson   
136   20170215      theft   
137   20

___

## Resolviendo el Misterio (y verificando si resolviste el caso)

De aquí en adelante, usarás tus habilidades y las pistas en la base de datos del Departamento de Policía para encontrar al asesino. Cuando creas que has encontrado al asesino, vuelve a esta sección y usa la celda de abajo para verificar tu respuesta y ver si encontraste al asesino:

ejemplo:
```python
check_suspect("Adam Levine")
```

In [ ]:
check_suspect("Jeremy Bowers")

Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge,try querying the interview transcript of the murderer to find the real villain behind this crime.If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries.
Use this same `check_suspect` function with your new suspect to check your answer.


True

## Espacio de Trabajo

Usa las celdas de abajo para escribir tus consultas y trabajar en resolver el misterio. Cuando tengas un sospechoso, verifica tu respuesta usando la [celda arriba de esta](#solving-the-mystery-and-checking-if-you-cracked-the-case) y ejecuta su nombre a través de la función `check_suspect`. Si encuentras al asesino, la función te lo dirá.

No olvides usar `%%sql` en la parte superior de las celdas de `Code` que crees para que tus consultas SQL funcionen. ¡Buena suerte, detectives!

## **FILTRAR DATOS DE LA TABLA CRIME_SCENE_REPORT**

Se filtra el contenido de la tabla CRIME_SCENE_REPORT, para obtener solo la informacion de apropiada: murder, fecha del asesinato (15 de Enero de 2018), y el lugar (SQL City).

In [ ]:
%%sql
/*
  Filtrar la info por "murder", el 15 de enero del 2018 en sql city
*/
SELECT *
FROM crime_scene_report
WHERE type = 'murder' AND date = (20180115) AND city = 'SQL City'

date    type  \
0  20180115  murder   

                                                                                          description  \
0  Security footage shows that there were 2 witnesses. The first witness lives at the last house o...   

       city  
0  SQL City

## **INFORMACIÓN DE LOS TESTIGOS DEL ASESINATO**

Las imágenes de seguridad muestran que hubo 2 testigos. El primer testigo vive en la última casa de la calle "Northwestern Dr". El segundo testigo, llamado Annabel, vive en algún lugar de la calle "Franklin Ave"

In [ ]:
%%sql
/*
  Primer testigo - ultima casa en "Northwestern Dr"
*/
SELECT *
FROM person
WHERE address_street_name	= 'Northwestern Dr'
ORDER BY address_number DESC
LIMIT 1

id            name  license_id  address_number address_street_name        ssn
0  14887  Morty Schapiro      118009            4919     Northwestern Dr  111564949

Morty Schapiro	es el primer testigo

In [ ]:
%%sql
/*
    Segundo testigo, Annabel, - en algun lugar de "Franklin Ave"
*/
SELECT *
FROM person
WHERE address_street_name	= 'Franklin Ave'
AND name LIKE 'Annabel%'
/*
'Annabel', '%' comienza con "Annabel" y que luego tenga cualquier combinación de caracteres después.
*/

id            name  license_id  address_number address_street_name        ssn
0  16371  Annabel Miller      490173             103        Franklin Ave  318771143

## **ENCONTRAR ENTREVISTAS DE LOS TESTIGOS**

Una vez que obtuvimos los id de los testigos, buscamos sus entrevistas

In [ ]:
%%sql
/*
    Segundo testigo, Annabel, - en algun lugar de "Franklin Ave"
*/
SELECT *
FROM interview
WHERE person_id IN ('16371', '14887');


person_id  \
0      16371   
1      14887   

                                                                                           transcript  
0  I saw the murder happen, and I recognized the killer from my gym when I was working out last we...  
1  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership nu...

## **ENCONTRAR AL SOSPECHOSO**

De acuerdo con las entrevistas el sospechoso asistió al gimnasio el 09 de enero,es un hombre que tiene membresía Gold en el gimnasio Get Fit Now Gym. Llevaba una bolsa cuyos primeros numeros eran "48Z" y placa del auto "H42W".

Buscamos la placa que tenga H42W en sus numeros

In [ ]:
%%sql

SELECT *
FROM drivers_license
WHERE plate_number LIKE '%H42W%'

id  age  height eye_color hair_color  gender plate_number   car_make car_model
0  183779   21      65      blue     blonde  female       H42W0X     Toyota     Prius
1  423327   30      70     brown      brown    male       0H42W2  Chevrolet  Spark LS
2  664760   21      71     black      black    male       4H42WR     Nissan    Altima

De las 3 coincidencias, verificar la identidad de los dueños de los autos.

In [ ]:
%%sql

SELECT *
FROM person
WHERE license_id IN ('183779','423327','664760')

id            name  license_id  address_number    address_street_name        ssn
0  51739  Tushar Chandra      664760             312                 Phi St  137882671
1  78193  Maxine Whitely      183779             110                Fisk Rd  137882671
2  67318   Jeremy Bowers      423327             530  Washington Pl, Apt 3A  871539279

De esta busqueda, logramos obtener los ID de las 3 personas. Comparamos con los ID de los miembros GOLD con member id "48Z".

In [ ]:
%%sql

SELECT *
FROM get_fit_now_member
WHERE membership_status = 'gold' AND id IN ('48Z7A', '48Z55')

id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

Obtenemos una coincidencia, Jeremy Bowers con el person_is 67318.

In [ ]:
check_suspect("Jeremy Bowers")

Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge,try querying the interview transcript of the murderer to find the real villain behind this crime.If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries.
Use this same `check_suspect` function with your new suspect to check your answer.


True

Buscamos la entrevista de Jeremy Bowers

In [ ]:
%%sql

SELECT *
FROM interview
WHERE person_id IN ('67318')

person_id  \
0      67318   

                                                                                           transcript  
0  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" ...

Con esto confirmamos que Jeremy Bowers es el *asesino*, pero fue contratado.
Indica lo siguiente: "Fui contratado por una mujer con mucho dinero. No sé su nombre, pero sé que mide alrededor de 5'5" (65") o 5'7" (67"). Tiene cabello rojo y conduce un Tesla Model S. Sé que asistió al concierto de SQL Symphony 3 veces en diciembre de 2017."

Con esto filtramos la informacion en drivers_license de acuerdo a la descripción

In [ ]:
%%sql

SELECT *
FROM drivers_license
WHERE hair_color = 'red' AND car_make = 'Tesla' AND gender = 'female'

id  age  height eye_color hair_color  gender plate_number car_make car_model
0  202298   68      66     green        red  female       500123    Tesla   Model S
1  291182   65      66      blue        red  female       08CM64    Tesla   Model S
2  918773   48      65     black        red  female       917UU3    Tesla   Model S

con el ID obtenido, determinamos el licence_id de cada dueño para ver sus nombres.

In [ ]:
%%sql

SELECT *
FROM person
WHERE license_id IN ('202298', '291182', '918773')

id              name  license_id  address_number address_street_name        ssn
0  78881          Red Korb      918773             107         Camerata Dr  961388910
1  99716  Miranda Priestly      202298            1883          Golden Ave  987756388
2  90700     Regina George      291182             332           Maple Ave  337169072

Comparamos el id de las sospechosas, con el id de quien asistio al concierto


In [ ]:
%%sql

SELECT *
FROM facebook_event_checkin
WHERE person_id IN ('78881',	'99716', '90700')

person_id  event_id            event_name      date
0      99716      1143  SQL Symphony Concert  20171206
1      99716      1143  SQL Symphony Concert  20171212
2      99716      1143  SQL Symphony Concert  20171229

Miranda Priestly con el id 99716, asistio 3 veces al concierto SQL Symphony. Por lo cual es la a asesina.


In [ ]:
check_suspect("Miranda Priestly")

Congrats, you found the brains behind the murder!
Everyone in SQL City hails you as the greatest SQL detective of all time.
Time to break out the champagne!


True